apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: big-query-db
  description: BigQuery DB
  tags:
    - sql
    - ford
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=big-query-db,tier=backenddb'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: it
  system: ford-pro-system
