apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ford-motor-catalog
  description: Ford Tech Resource Catalog
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/ford-pro-ui/ford-pro-ui.yaml
