tap_gui:
  app_config:
    techdocs:
      builder: 'external'
      publisher:
        type: 'awsS3'
        awsS3:
          bucketName: ford-demo-20220506
          credentials:
            accessKeyId: 
            secretAccessKey: 
          region: us-east-1
          s3ForcePathStyle: false