apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ford-pro-group
  description: Ford Pro
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: pro@ford.com
    picture: https://content.fordpro.com/content/dam/fordpro/us/en-us/images/shared/ford-pro-logo.svg
  parent: development
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: asaikali
spec:
  profile:
    displayName: Adib Saikali
    email: asaikali@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [ford-pro-group,it,connected-vehicle]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cgsamp
spec:
  profile:
    displayName: Chris Samp
    email: csamp@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [ford-pro-group,it,connected-vehicle]
  owner: ford-motor-company
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest1@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [ford-pro-group]
