apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ford-motor-company
  description: Ford Motor Company
  links:
    - url: http://www.ford.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Ford Motor Company
    email: mike@ford.com
    picture: https://corporate.ford.com/content/dam/corporate/us/en-us/icons/ford-logo.png
  children: [it,development]
