apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ford-motor-company
  description: Ford Motor Company
  links:
    - url: http://www.ford.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Ford Motor Company
    email: demo@example.com
    picture: https://corporate.ford.com/content/dam/corporate/us/en-us/icons/ford-logo.png
  children: [it,development]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ford-technology
  description: Ford Technology
spec:
  targets:
    - ./it-dept.yaml
    - ./dev-dept.yaml
    - ./ford-pro.yaml
    - ./foundational-services.yaml
